<?php
/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16.1|configurator
 * you can change this configuration by importing this file.
 */
return PhpCsFixer\Config::create()
    ->setRules([
        'binary_operator_spaces' => true,
        'array_indentation' => true,
        'blank_line_after_namespace' => true,
        'braces' => true,
        'cast_spaces' => true,
        'class_attributes_separation' => true,
        'class_definition' => true,
        'class_keyword_remove' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'whitespace_after_comma_in_array' => true,
        'ternary_operator_spaces' => true,
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_align' => true,
        'no_leading_import_slash' => true,
        'no_closing_tag' => true,
        'multiline_whitespace_before_semicolons' => true,
        'lowercase_constants' => true,
        'constant_case' => true,
        'align_multiline_comment' => true,
        'linebreak_after_opening_tag' => true,
        'unary_operator_spaces' => true,
        'switch_case_semicolon_to_colon' => true,
        'standardize_not_equals' => true,
        'standardize_increment' => true,
        'space_after_semicolon' => true,
        'single_quote' => true,
        'single_blank_line_at_eof' => true,
        'include' => true,
        'elseif' => true,
        'concat_space' => ['spacing'=>'one'],
        'array_syntax' => true,
        'backtick_to_shell_exec' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'doctrine_annotation_indentation' => true,
        'doctrine_annotation_spaces' => true,
        'single_line_comment_style' => true,
        'trailing_comma_in_multiline_array' => true,
        'single_import_per_statement' => true,
        'semicolon_after_instruction' => true,
        'full_opening_tag' => true,
        'function_declaration' => true,
        'function_typehint_space' => true,
        'line_ending' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_whitespace_in_blank_line' => true,
        'php_unit_method_casing' => true,
        'short_scalar_cast' => true,
        'single_line_throw' => true,
        'switch_case_space' => true,
        'single_class_element_per_statement' => true,
        'simplified_null_return' => true,
        'normalize_index_brace' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_useless_return' => true,
        'no_trailing_whitespace' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => true,
        'no_spaces_inside_parenthesis' => true,
        'no_short_bool_cast' => true,
        'no_leading_namespace_whitespace' => true,
        'new_with_braces' => true,
        'no_alternative_syntax' => true,
        'magic_method_casing' => true,
        'lowercase_cast' => true,
        'indentation_type' => true,
        'explicit_string_variable' => true,
        'escape_implicit_backslashes' => true,
        'declare_equal_normalize' => ['space'=>'single'],
        'doctrine_annotation_array_assignment' => true,
        'increment_style' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'lowercase_keywords' => true,
        'compact_nullable_typehint' => true,
        'explicit_indirect_variable' => true,
        'final_static_access' => true,
        'heredoc_to_nowdoc' => true,
        'method_argument_space' => true,
        'method_chaining_indentation' => true,
        'multiline_comment_opening_closing' => true,
        'native_function_casing' => true,
        'native_function_type_declaration_casing' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_break_comment' => true,
        'no_mixed_echo_print' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_curly_braces' => true,
        'phpdoc_line_span' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => true,
        'phpdoc_trim' => true,
        'trim_array_spaces' => true,
        'simple_to_complex_string_variable' => true,
        'return_type_declaration' => true,
        'phpdoc_types' => true,
        'phpdoc_scalar' => true,
        'no_unneeded_control_parentheses' => true,
        'single_line_after_imports' => true,
        'encoding' => true,
        'visibility_required' => true,
    ])
    ->setFinder(PhpCsFixer\Finder::create()
        ->exclude('vendor')
        ->in(__DIR__)
    )
;
